version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./map
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge